### ISSUE TITLE
3ds max error

### ISSUE THREAD

**Issue by HorseTrain** [Makiah/BotW-SBFRES-to-FBX#12]
When I try to load your ms script to 3ds max, it gives me "Unable to convert undefined to type: Integer 64"

**Comment by Makiah** [comment]
That's unfortunately just an issue with certain models, and I honestly have no idea how to fix it since I didn't write the MS scripts.  [Random Talking Bush](https://www.vg-resource.com/thread-29836.html) (script author) might have more to say about this issue, perhaps it'll be fixed in a future release?  As for now, most models can be extracted fine, my guess is that the more complex ones such as high-poly terrain are a bit harder.
