### ISSUE TITLE
Recommendation: Stick to FBX for primary model output

### ISSUE THREAD

**Issue by JakoNintenCraft** [Makiah/BotW-SBFRES-to-FBX#2]
Hey again! Just want to express an opinion of mine about the move from FBX exporting to OBJ exporting you're working on, and while it might be a good thing to have another format to convert to, I would not recommend that you replace the FBX functionality altogether, as there are several instances in which using OBJ instead of FBX would detract from the experience of the end user.

1. Lack of hierarchy support: due to the OBJ format lacking 1st party support for skinning or mesh deformation (among other things), exporting in OBJ format will cause there to be no skeleton data for the models.  Most modelers would want this feature retained for things like animation, so keep it in mind.
AND
2. Lack of support for normal, specular, and bump maps: these are often what give BOTW's models their characteristic appearance and are needed to have truly accurate rips of said models.

If you are really bent on including this functionality, then include it in a separate branch or add said functionality alongside the already existing FBX exporting capability; not replacing FBX exporting outright, as FBX supports more features than the more limited (but more accessible) OBJ specification.

Hope this helps!

**Comment by Makiah** [comment]
I completely agree, my last commit was amidst a bit of frustration over odd FBX exports (tiny pieces of models sometimes didn't align correctly, etc.), and so I was looking for solutions.  This was a pretty bad one that I hadn't recognized at the time, but after a bit of research, it became apparent that OBJ was definitely inferior to FBX.  I haven't really changed anything in the repo since, which is why that shift doesn't seem to have changed.
